output: docs
author: gematik Gesellschaft für Telematikanwendungen der Gesundheitskarte mbH
author_url: http://www.gematik.de
exclude: /*/internal*
module: CardReaderProviderApi
github_url: http://www.github.com/gematik/CardReaderProviderApi-swift.git
theme: jony
xcodebuild_arguments:
  - "-project"
  - 'CardReaderProviderApi.xcodeproj'
